name:                 tamarin-prover-accountability
version:              1.9.0
visibility:           public
id:                   tamarin-prover-accountability-1.9.0-4eyvgcz8u2nJQo4S3PR0aL
key:                  tamarin-prover-accountability-1.9.0-4eyvgcz8u2nJQo4S3PR0aL
license:              LicenseRef-GPL
copyright:            (c) 2019-2021 Robert Künnemann, Kevin Morio & Yavor Ivanov
maintainer:           Robert Künnemann <robert@kunnemann.de>
author:
    Robert Künnemann <robert@kunnemann.de>,
    Kevin Morio <kevin.morio@cispa.de>,
    Yavor Ivanov <yavor.ivanov@cispa.de>

homepage:             https://tamarin-prover.github.io/
synopsis:             Library for accountability for the tamarin prover.
description:
    This is an internal library of the Tamarin prover for
    security protocol verification
    (<hackage.haskell.org/package/tamarin-prover>).

    This library provides support for accountability verification.

category:             Theorem Provers
abi:                  f644139fb52a73eb66cbdb605fd33d04
exposed:              True
exposed-modules:      Accountability Accountability.Generation
import-dirs:
    /Users/sofiagiampietro/Documents/tamarin-bilinear-pairings/bp-tamarin-source/tamarin-prover/.stack-work/install/x86_64-osx/b6257c784c2bc0020026b0a5507581a4d35623dc1dbd6dc7437d2f158fb4918a/9.2.8/lib/x86_64-osx-ghc-9.2.8/tamarin-prover-accountability-1.9.0-4eyvgcz8u2nJQo4S3PR0aL

library-dirs:
    /Users/sofiagiampietro/Documents/tamarin-bilinear-pairings/bp-tamarin-source/tamarin-prover/.stack-work/install/x86_64-osx/b6257c784c2bc0020026b0a5507581a4d35623dc1dbd6dc7437d2f158fb4918a/9.2.8/lib/x86_64-osx-ghc-9.2.8/tamarin-prover-accountability-1.9.0-4eyvgcz8u2nJQo4S3PR0aL

dynamic-library-dirs:
    /Users/sofiagiampietro/Documents/tamarin-bilinear-pairings/bp-tamarin-source/tamarin-prover/.stack-work/install/x86_64-osx/b6257c784c2bc0020026b0a5507581a4d35623dc1dbd6dc7437d2f158fb4918a/9.2.8/lib/x86_64-osx-ghc-9.2.8

data-dir:
    /Users/sofiagiampietro/Documents/tamarin-bilinear-pairings/bp-tamarin-source/tamarin-prover/.stack-work/install/x86_64-osx/b6257c784c2bc0020026b0a5507581a4d35623dc1dbd6dc7437d2f158fb4918a/9.2.8/share/x86_64-osx-ghc-9.2.8/tamarin-prover-accountability-1.9.0

hs-libraries:
    HStamarin-prover-accountability-1.9.0-4eyvgcz8u2nJQo4S3PR0aL

depends:
    aeson-2.0.3.0-B56EwkCboVUIb59k2pHz9h
    aeson-pretty-0.8.9-8noA6L0a6TLBaZAhq7is5s base-4.16.4.0
    binary-0.8.9.0 bytestring-0.11.4.0 containers-0.6.5.1
    deepseq-1.4.6.1 dlist-1.0-BTRLt86GCjZCd2v5iuhai4 exceptions-0.10.4
    fclabels-2.0.5.1-JJ7GOPNjeAuDPC4Kbx7lhR mtl-2.2.2
    parallel-3.2.2.0-KgDyPHm89eYAjQsIhXthC1 parsec-3.1.15.0
    process-1.6.16.0 raw-strings-qq-1.1-EH0X2H1VTcCF8RWb3zpG1w
    safe-0.3.19-3Atv9xv1FTZE5WsEtdRBSd
    tamarin-prover-term-1.9.0-8MHBmfQJPGECAvYH9jtVtl
    tamarin-prover-theory-1.9.0-GcQn8RhyXYVIBvrIrcEhiR
    tamarin-prover-utils-1.9.0-GF6vzZf7ldAASd9GaqAcZl text-1.2.5.0
    transformers-0.5.6.2 uniplate-1.6.13-XIIycvvBL3urctcnUq6F

haddock-interfaces:
    /Users/sofiagiampietro/Documents/tamarin-bilinear-pairings/bp-tamarin-source/tamarin-prover/.stack-work/install/x86_64-osx/b6257c784c2bc0020026b0a5507581a4d35623dc1dbd6dc7437d2f158fb4918a/9.2.8/doc/tamarin-prover-accountability-1.9.0/tamarin-prover-accountability.haddock

haddock-html:
    /Users/sofiagiampietro/Documents/tamarin-bilinear-pairings/bp-tamarin-source/tamarin-prover/.stack-work/install/x86_64-osx/b6257c784c2bc0020026b0a5507581a4d35623dc1dbd6dc7437d2f158fb4918a/9.2.8/doc/tamarin-prover-accountability-1.9.0
