/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package tamarin-prover-theory-1.9.0 */
#ifndef VERSION_tamarin_prover_theory
#define VERSION_tamarin_prover_theory "1.9.0"
#endif /* VERSION_tamarin_prover_theory */
#ifndef MIN_VERSION_tamarin_prover_theory
#define MIN_VERSION_tamarin_prover_theory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_tamarin_prover_theory */
/* package HUnit-1.6.2.0 */
#ifndef VERSION_HUnit
#define VERSION_HUnit "1.6.2.0"
#endif /* VERSION_HUnit */
#ifndef MIN_VERSION_HUnit
#define MIN_VERSION_HUnit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_HUnit */
/* package aeson-2.0.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.0.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package aeson-pretty-0.8.9 */
#ifndef VERSION_aeson_pretty
#define VERSION_aeson_pretty "0.8.9"
#endif /* VERSION_aeson_pretty */
#ifndef MIN_VERSION_aeson_pretty
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_aeson_pretty */
/* package array-0.5.4.0 */
#ifndef VERSION_array
#define VERSION_array "0.5.4.0"
#endif /* VERSION_array */
#ifndef MIN_VERSION_array
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_array */
/* package attoparsec-0.14.4 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.14.4"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 4)
#endif /* MIN_VERSION_attoparsec */
/* package base-4.16.4.0 */
#ifndef VERSION_base
#define VERSION_base "4.16.4.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  16 || \
  (major1) == 4 && (major2) == 16 && (minor) <= 4)
#endif /* MIN_VERSION_base */
/* package binary-0.8.9.0 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.9.0"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.11.4.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.4.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 4)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.5.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.5.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_VERSION_containers */
/* package deepseq-1.4.6.1 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.6.1"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 6)
#endif /* MIN_VERSION_deepseq */
/* package dlist-1.0 */
#ifndef VERSION_dlist
#define VERSION_dlist "1.0"
#endif /* VERSION_dlist */
#ifndef MIN_VERSION_dlist
#define MIN_VERSION_dlist(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_dlist */
/* package exceptions-0.10.4 */
#ifndef VERSION_exceptions
#define VERSION_exceptions "0.10.4"
#endif /* VERSION_exceptions */
#ifndef MIN_VERSION_exceptions
#define MIN_VERSION_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_VERSION_exceptions */
/* package fclabels-2.0.5.1 */
#ifndef VERSION_fclabels
#define VERSION_fclabels "2.0.5.1"
#endif /* VERSION_fclabels */
#ifndef MIN_VERSION_fclabels
#define MIN_VERSION_fclabels(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 5)
#endif /* MIN_VERSION_fclabels */
/* package filepath-1.4.2.2 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.2"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package parallel-3.2.2.0 */
#ifndef VERSION_parallel
#define VERSION_parallel "3.2.2.0"
#endif /* VERSION_parallel */
#ifndef MIN_VERSION_parallel
#define MIN_VERSION_parallel(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_parallel */
/* package parsec-3.1.15.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.15.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 15)
#endif /* MIN_VERSION_parsec */
/* package pretty-1.1.3.6 */
#ifndef VERSION_pretty
#define VERSION_pretty "1.1.3.6"
#endif /* VERSION_pretty */
#ifndef MIN_VERSION_pretty
#define MIN_VERSION_pretty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_pretty */
/* package primitive-0.7.3.0 */
#ifndef VERSION_primitive
#define VERSION_primitive "0.7.3.0"
#endif /* VERSION_primitive */
#ifndef MIN_VERSION_primitive
#define MIN_VERSION_primitive(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 3)
#endif /* MIN_VERSION_primitive */
/* package process-1.6.16.0 */
#ifndef VERSION_process
#define VERSION_process "1.6.16.0"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 16)
#endif /* MIN_VERSION_process */
/* package regex-pcre-builtin-0.95.2.3.8.44 */
#ifndef VERSION_regex_pcre_builtin
#define VERSION_regex_pcre_builtin "0.95.2.3.8.44"
#endif /* VERSION_regex_pcre_builtin */
#ifndef MIN_VERSION_regex_pcre_builtin
#define MIN_VERSION_regex_pcre_builtin(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  95 || \
  (major1) == 0 && (major2) == 95 && (minor) <= 2)
#endif /* MIN_VERSION_regex_pcre_builtin */
/* package regex-posix-0.96.0.1 */
#ifndef VERSION_regex_posix
#define VERSION_regex_posix "0.96.0.1"
#endif /* VERSION_regex_posix */
#ifndef MIN_VERSION_regex_posix
#define MIN_VERSION_regex_posix(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  96 || \
  (major1) == 0 && (major2) == 96 && (minor) <= 0)
#endif /* MIN_VERSION_regex_posix */
/* package safe-0.3.19 */
#ifndef VERSION_safe
#define VERSION_safe "0.3.19"
#endif /* VERSION_safe */
#ifndef MIN_VERSION_safe
#define MIN_VERSION_safe(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 19)
#endif /* MIN_VERSION_safe */
/* package split-0.2.3.5 */
#ifndef VERSION_split
#define VERSION_split "0.2.3.5"
#endif /* VERSION_split */
#ifndef MIN_VERSION_split
#define MIN_VERSION_split(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_split */
/* package tamarin-prover-term-1.9.0 */
#ifndef VERSION_tamarin_prover_term
#define VERSION_tamarin_prover_term "1.9.0"
#endif /* VERSION_tamarin_prover_term */
#ifndef MIN_VERSION_tamarin_prover_term
#define MIN_VERSION_tamarin_prover_term(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_tamarin_prover_term */
/* package tamarin-prover-utils-1.9.0 */
#ifndef VERSION_tamarin_prover_utils
#define VERSION_tamarin_prover_utils "1.9.0"
#endif /* VERSION_tamarin_prover_utils */
#ifndef MIN_VERSION_tamarin_prover_utils
#define MIN_VERSION_tamarin_prover_utils(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_tamarin_prover_utils */
/* package text-1.2.5.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.5.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_text */
/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */
/* package uniplate-1.6.13 */
#ifndef VERSION_uniplate
#define VERSION_uniplate "1.6.13"
#endif /* VERSION_uniplate */
#ifndef MIN_VERSION_uniplate
#define MIN_VERSION_uniplate(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 13)
#endif /* MIN_VERSION_uniplate */

/* tool alex-3.2.7.4 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.2.7.4"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-17.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "17.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  17 || \
  (major1) == 17 && (major2) <  0 || \
  (major1) == 17 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.2.8 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.2.8"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.2.8 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.2.8"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.26.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.26.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-1.20.1.1 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.20.1.1"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.2.8 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.2.8"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "tamarin-prover-theory-1.9.0-GcQn8RhyXYVIBvrIrcEhiR"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "tamarin-prover-theory-1.9.0-GcQn8RhyXYVIBvrIrcEhiR"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.9.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
